FROM httpd:2.4

COPY ./fmu/ /usr/local/apache2/htdocs/fmu/
COPY ./is-cole-winning/ /usr/local/apache2/htdocs/is-cole-winning/
COPY ./media/ /usr/local/apache2/htdocs/media/
COPY ./index/ /usr/local/apache2/htdocs/